### ISSUE TITLE
Hi, i want to try your script in my NAS, but when i start it......

### ISSUE THREAD

**Issue by ilvise** [alfem/telegram-downloader-bot#1]
i@ThinkPad:~/Developer/telegram-downloader-bot$ python2 telegram-download-bot.py 
Traceback (most recent call last):
  File "telegram-download-bot.py", line 88, in <module>
    if user_command.lower() == "quit":
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by alfem** [comment]
Have you set up your credentials and chat_id ?

**Comment by rdlmda** [comment]
Same issue for me with the same error message.

I'm running Python 2.7 on Docker alpine and I've installed the following modules:
- python-telegram-bot
- requests (undocumented dependency)

I have:

- registered a bot with Botfather and obtained the token
- obtained my chat id

I start `telegram-download-bot.py` and receive two Telegram messages from the bot:
- "Downloader ready!"
- "Share your file posts with me and I will download them for you."

Then, imeddiately, I get the same error.

```
Traceback (most recent call last):
  File "telegram-download-bot.py", line 88, in <module>
    if user_command.lower() == "quit":
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by alfem** [comment]
It should be fixed now. Please, test it and report any issues.
