### ISSUE TITLE
Feature Request: allow download big files

### ISSUE THREAD

**Issue by AmezcuaGil** [alfem/telegram-downloader-bot#16]
Awesome project dude.
Is it possible to modify the script to allow download of big files?

I did some dig and found the following: https://weekly-geekly.github.io/articles/348234/index.html

**Comment by baruchiro** [comment]
@alfem What do you think?
I configured all my system now, and in the end I can't download the file...

**Comment by alfem** [comment]
I will take a look as soon as I get my laptop repaired. It is in the Acer service.

**Comment by alfem** [comment]
Meanwhile I have found this awesome project: https://github.com/Nekmo/telegram-upload

Do not get confused by the name. It also download files. You could set a service with the telegram-download script, using a channel_id and using the delete-after-download parameter ;-)

**Comment by alfem** [comment]
Here you have a brand new script, without the file size limit: https://github.com/alfem/telegram-download-daemon/

Help with testing is welcome
