### ISSUE TITLE
file too big issue

### ISSUE THREAD

**Issue by mzramna** [alfem/telegram-downloader-bot#19]
there is any way to increase file size limit?
or any way to put it to download the file into other download daemon like aria2?

**Comment by mzramna** [comment]
there is an way in fact:
https://stackoverflow.com/questions/51696860/python-telegram-bot-how-to-keep-the-bot-working-after-changing-the-code-and-re

you can use this link address `https://api.telegram.org/file/bot<token>/<file_path>`
and download it by other methods,since i'm not familiar to telegram bot api yet , i'm unable to use this,but since i'm able to it i will try to do it myself,but if you could begin or give any idea of how to do it i'm glad

**Comment by alfem** [comment]
Please, read this old issue #16 and the final solution.
