### ISSUE TITLE
No default language could be detect.

### ISSUE THREAD

**Issue by rafidalhaque** [alfem/telegram-downloader-bot#22]
Hi, 
When I deploy it to Heroku it had failed everytime. And saw me the messages, "No default language could be detected for this app." What should I do?

**Comment by alfem** [comment]
I do not use Heroku. Perhaps this answer could give you some clues: 

https://stackoverflow.com/questions/44232967/heroku-no-default-language-could-be-detected-for-this-app-for-python-even-with

**Comment by alfem** [comment]
I have addede the minimal Heroku configuration in runtime.txt.

Please, test it again.
