### ISSUE TITLE
telegram.error.BadRequest: File is too big

### ISSUE THREAD

**Issue by alr2413** [alfem/telegram-downloader-bot#4]
First, thanks for sharing this script.
I have a problem with this script. Whenever I try to download file with size ~300mb, it returns the following error:
telegram.error.BadRequest: File is too big.

I also have another question or request:
Can we also download files that we shared as "quick send" in telegram like mp4?

**Comment by alfem** [comment]
Reading [Telegram doc](https://core.telegram.org/bots/api):

> getFile
> 
> Use this method to get basic info about a file and prepare it for downloading. For the moment, bots can download files of up to 20MB in size.

So the 20Mb limit for bots depends on Telegram.

About the quick send, please elaborate the question in another issue, please. Right now I do not know what is that 'quick send'.
