### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by carpediem75** [alfem/telegram-downloader-bot#6]
This is what I get:
> python2 telegram-download-bot.py 
Traceback (most recent call last):
  File "telegram-download-bot.py", line 116, in <module>
    photo=photos[-1]
IndexError: list index out of range

the bot on Telegram say that all is OK but don't answer

**Comment by alfem** [comment]
What kind of message or content are you sending to the bot?

**Comment by carpediem75** [comment]
nothing.
 I run " python2 telegram-download-bot.py" in the folder of the project on ubuntu 18.04

**Comment by alfem** [comment]
are you reusing and old bot?

**Comment by carpediem75** [comment]
no.
if fixed the error adding an if to test if photos length is bigger than zero:
if (len(photos)>0):
                    photo=photos[-1]

but I don't understand why it happens, it is inside a try...
no I get another error:
    raise BadRequest(message)
telegram.error.BadRequest: File is too big

the file is a pdf of 2 megabyte

**Comment by alfem** [comment]
The 'try' only captures "AttributeError" exceptions.

About the file size, is a Telegram limit for bots, as I answered here: https://github.com/alfem/telegram-downloader-bot/issues/4
