### ISSUE TITLE
file is too big error

### ISSUE THREAD

**Issue by adocampo** [alfem/telegram-downloader-bot#7]
Hi there! 

I stumbled upon your bot and I loved because I like the one-file bot, and not those overcomplicated bots out there, nice job! :+1: 
 
I'm facing, but and isse with large files. I would like to send to my NAS tvshows files from other telegram groups/channels, and it seems normal bots cannot download/upload files greater than 20MB.

As I can't download the file, I've deleted that file I wanted to download, but now the bot automatically crashes
```bash
./telegram-download-bot.py 
Traceback (most recent call last):
  File "./telegram-download-bot.py", line 106, in <module>
    tfile=bot.getFile(newfile.file_id)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 1546, in get_file
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: File is too big
```

So, have you considered to use user bots instead normal bots to avoid the size limitation? Besides, is there any way to delete the "download queue" to let the bot start again?

Thank you!

**Comment by alfem** [comment]
When bot starts it ask for all the unprocessed messages. You can modify the bot to start with a certain number. 

Just change the line "update_id=0" and write in a number greater than the id of the big file message.

Alternatively you can wait for me to have time to add some code for exception handling :-D

**Comment by alfem** [comment]
Solved in latest versions

**Comment by adocampo** [comment]
Great, I'll try as soon as I can. So we are now able to download big files? So I think there would be no need to cancel the queue if something fails, or we can also cancel the queue?

**Comment by alfem** [comment]
Please, read this old issue: #4
