### ISSUE TITLE
Add multi-user support

### ISSUE THREAD

**Issue by samthelion** [alfem/telegram-downloader-bot#8]
Is there a way to specify more than one "TELEGRAM_CHAT_ID" so more than one telegram user can use it?

**Comment by alfem** [comment]
Just create a Telegram group and use that ID in the 'TELEGRAM_CHAT_ID' instead of an user id.

**Comment by samthelion** [comment]
> 
> 
> Just create a Telegram group and use that ID in the 'TELEGRAM_CHAT_ID' instead of an user id.

Cool, thanks!
